language: c

compiler: gcc

  
install:
  - git submodule update --remote
  - echo "Configure..."
  - cmake --no-warn-unused-cli -H. -B./build -G "Unix Makefiles"
  - echo "Build...."
  - cmake --build build --config Debug --target all

script: 
  - ./build/ElectionTester
