language: c

# install: make cmake gcc
# compiler: gcc

# matrix:
#   - os: linux
#   addons:
#     apt:
#       sources:
#         - ubuntu-toolchain-r-test
#       packages:
#         - g++-7

#   env:
#     - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

# before_install:
#   - eval "${MATRIX_EVAL}"
  


jobs:
  include:
    - stage: Configure
      script: cmake --no-warn-unused-cli -H. -B./build -G "Unix Makefiles"
    - stage: Build
      script: cmake --build build --config Debug --target all
    - stage: Test Election
      script: ./build/ElectionTester

# script: sh ./trigger_tests.sh
script: cmake --no-warn-unused-cli -H. -B./build -G "Unix Makefiles" && cmake --build build --config Debug --target all && ./build/ElectionTester